
source = style.conf

general {
    ignore_empty_input = true
    text_trim = true
}

animations {
    enabled = true
    bezier = linear, 0, 0, 1, 1
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    animation = fadeIn, 1, 15, linear
    animation = fadeOut, 1, 15, linear
    animation = InputFieldColors, 1, 2, linear
    animation = InputFieldFade, 1, 5, linear
    animation = InputFieldWidth, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $XDG_CACHE_HOME/wm/lockscreen_wallpaper.jpg
    color = rgba($background_color)
}

# Analog clock
image {
    monitor =
    path = /tmp/hyprlock_clock.png
    size = 480
    rounding = -1
    border_size = 0
    reload_time = 63
    reload_cmd = $XDG_CONFIG_HOME/hyprlock/generate_clock.py
    position = 0, 200
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 40
    outline_thickness = 3
    dots_size = 0.7
    dots_spacing = 0.3
    dots_center = false
    dots_rounding = 0
    outer_color = rgba($main_color)
    inner_color = rgba($background_color)
    font_color = rgba($main_color)
    font_family = $font
    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <i>$PAMPROMPT</i>
    hide_input = false
    rounding = 8
    check_color = rgba($green)
    fail_color = rgba($red)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 1000
    capslock_color = rgba($foreground_color)
    numlock_color = rgba($main_color)
    bothlock_color = rgba($foreground_color)
    invert_numlock = false
    swap_font_color = false
    position = 0, 30
    halign = center
    valign = bottom
    zindex = 1
    shadow_passes = 1
}

# Login info
label {
    monitor =
    text = <b>$FAIL</b>
    color = rgba($foreground_color)
    font_size = 20
    font_family = $font
    position = 0, 30
    halign = center
    valign = bottom
    zindex = 0
    shadow_passes = 1
}

# Layout button
label {
    monitor =
    text = 󰌌  $LAYOUT
    color = rgba($foreground_color)
    font_size = 20
    font_family = $font
    position = 30, 30
    halign = left
    valign = bottom
    shadow_passes = 1

    onclick = niri msg action switch-layout next
}

# Log out button
label {
    monitor =
    text = 󰍃
    color = rgba($foreground_color)
    font_size = 20
    font_family = $icons
    position = -130, 30
    halign = right
    valign = bottom
    shadow_passes = 1

    onclick = $XDG_CONFIG_HOME/niri/scripts/niri-shutdown.sh logout
}

# Reboot Button
label {
    monitor =
    text = 
    color = rgba($foreground_color)
    font_size = 20
    font_family = $icons
    position = -80, 30
    halign = right
    valign = bottom
    shadow_passes = 1

    onclick = $XDG_CONFIG_HOME/niri/scripts/niri-shutdown.sh reboot
}

# Shutdown Button
label {
    monitor =
    text = 
    color = rgba($foreground_color)
    font_size = 20
    font_family = $icons
    position = -30, 30
    halign = right
    valign = bottom
    shadow_passes = 1

    onclick = $XDG_CONFIG_HOME/niri/scripts/niri-shutdown.sh poweroff
}
