
include font.conf
include theme.conf
include bindings.conf

cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 2.5
cursor_underline_thickness 2.5
cursor_blink_interval 0.8
cursor_stop_blinking_after 10.0

cursor_trail 50
cursor_trail_decay 0.2 0.6
cursor_trail_start_threshold 2
cursor_trail_color none

scrollback_lines 2000
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.5
scrollbar_hover_width 0.75
scrollbar_radius 0.5
scrollbar_gap 0.25
scrollbar_min_handle_height 1.25
scrollbar_hitbox_expansion 0.25
scrollbar_handle_opacity 0.3
scrollbar_track_opacity 0.75
scrollbar_track_hover_opacity 0.5
scrollbar_handle_color foreground
scrollbar_track_color selection_background
progress_bar bottom

scrollback_pager_history_size 32

scrollback_fill_enlarged_window no
wheel_scroll_multiplier 5.0
wheel_scroll_min_lines 1
touch_scroll_multiplier 1.0
pixel_scroll yes

mouse_hide_wait 3.0

url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
url_excluded_characters
show_hyperlink_targets never
underline_hyperlinks hover

copy_on_select no
clear_selection_on_clipboard_loss no
paste_actions quote-urls-at-prompt,replace-newline,confirm,confirm-if-large
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#
select_by_word_characters_forward

click_interval -1.0
focus_follows_mouse yes
pointer_shape_when_grabbed arrow
default_pointer_shape arrow
pointer_shape_when_dragging beam crosshair
drag_threshold 5

enable_audio_bell no
visual_bell_duration 1.0
visual_bell_color none
window_alert_on_bell yes

remember_window_size  yes
initial_window_width  60c
initial_window_height 100c
remember_window_position no

window_resize_step_cells 2
window_resize_step_lines 2
window_border_width 3
draw_minimal_borders yes
draw_window_borders_for_single_window no
window_margin_width 0
single_window_margin_width -1
window_padding_width 0
single_window_padding_width -1
placement_strategy center

hide_window_decorations yes
resize_debounce_time 0.1 0.5
resize_in_steps no
confirm_os_window_close -1 count-background
window_drag_tolerance 2
window_title_bar top
window_title_bar_min_windows 0
window_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.window}{progress_percent}{title}"
active_window_title_template none
window_title_bar_active_foreground none
window_title_bar_active_background none
window_title_bar_inactive_foreground none
window_title_bar_inactive_background none
window_title_bar_align center

tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.75
tab_bar_style separator
tab_bar_align left
tab_bar_show_new_tab_button no
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_separator " "
tab_activity_symbol none
tab_title_max_length 30

update_check_interval 0
auto_reload_config -1
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_max_size 512
allow_hyperlinks yes
shell_integration no-cursor
allow_cloning ask
notify_on_cmd_finish unfocused 15 notify-bell focus
term xterm-kitty
terminfo_type direct
forward_stdio no

macos_option_as_alt yes
macos_hide_from_tasks no
macos_quit_when_last_window_closed yes
macos_window_resizable yes
macos_show_window_title_in menubar
macos_menubar_title_max_length 0

allow_remote_control yes
# listen_on unix:@mykitty
listen_on unix:/tmp/mykitty
