# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [ 2, 3, 5 ]
sort_by = "natural"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "drag", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 900
max_height      = 1200
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75

[tasks]
micro_workers    = 16
macro_workers    = 8
bizarre_retry    = 3
image_alloc      = 536870912  # 512MB
image_bound      = [ 10000, 10000 ]
suppress_preload = false

[opener]
extract = [
	{ run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[plugin]
prepend_fetchers = [
    { id = "git", run = "git", url = "*" },
    { id = "git", run = "git", url = "*/" },
]

prepend_previewers = [
    { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch --archive-icon='🗄️ ' --show-file-icons" },
    { mime = "application/bittorrent", run = "torrent-preview" },
    { url = "*.{csv,tsv}", run = 'piper -- bat -p --color=always "$1"' },
    { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
    { url = '**/.git/', run = 'preview-git' },
    { mime = 'audio/mpegurl', run = 'code' }, # ignore .m3u files
    { mime = 'audio/*', run = 'preview-audio' },
    { mime = '*.flac', run = 'preview-audio' },
    { url = "*.{lua,c,cpp,h,hpp,txt,py}", run = "code" },
]

prepend_preloaders = [
    { mime = 'audio/mpegurl', run = 'code' }, # ignore .m3u files
    { mime = 'audio/*', run = 'preview-audio' },
    { mime = '*.flac', run = 'preview-audio' },
]

prepend_spotters = [
    { mime = "image/*", run = "spot-image" },
    { url = "video/*", run = "spot-video" },
    { mime = 'audio/mpegurl', run = 'code' },
    { url = "audio/*", run = "spot-audio" },
    { url = "*.flac", run = "spot-audio" },
]
